== Blue harvest Customer management Portal
image:https://ci.spring.io/api/v1/teams/spring-boot/pipelines/spring-boot-3.2.x/jobs/build/badge["Build Status", link="https://ci.spring.io/teams/spring-boot/pipelines/spring-boot-3.2.x?groups=Build"] image:https://badges.gitter.im/Join Chat.svg["SonarQuality",link="https://sonar.im/spring-projects/spring-boot?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=sonaryQuality"]

:docs: https://docs.spring.io/spring-boot/docs/current-SNAPSHOT/reference
:github: https://github.com/spring-projects/spring-boot

== Introduction

 {project-name} aims at providing the customer account infromation from blue harvest paortal , this API is used by the front end customer management portal.

== Technical Stack

   This API mainly uses spring boot Framework for the API creations,
   Spring security backed Keycloak for the authentication and authrorization of the api based ont the roles and scopes subsribed for the user.
    And it holds the data in H2 inmemory database.

== Purpose and main rule

  This service sotres and exposes the customer account information and managed the transactions related to the customer account.

== Global workflow and detailed Process
    The multi module proejct contains differnt client and API modues

== Modules

   There are several modules in this customer managmenet protal
   Here is a quick overview:
   customer-information-api
   transaction-management-client
   transaction-management-api

== customer-information-api
     This api holds the customer referential information and kyc details which providet the basic information about the customer and let's the customer to handle the transactions fromt the front end portal.
      This API exposes two main endpoints
      Post (Creation of User Account) :
      Get (Consult the account information and it's related transactions)


== transactions-management-api
     This api holds the transaction information of the customers
      This API exposes two main endpoints
      Post (Creation of new transaction) :
      Get (Consult the transactiosn involved in the account)

== Transaction management client

   This module is used with spring webflux reactive version, inorder to augment the the performance of the api in reactive way.
   The cient stub is generated via the open API plugin where it has generated the webclient with the swagger documentation.
   This mdoule does provide the authenticatio and authorization of the api with spring security.

== License

    This API is licensed to blue harvest management , for any queries contant api bank support.
